services:
    paper:
      image: jaminima/fabric
      stdin_open: true
      tty: true
      ports:
        - "24565:25565"
      volumes:
        - ./server:/minecraft
        - ./mods:/minecraft-init/mods
